
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-happycows-s23-6pm-4
owner: ucsb-cs156-s23
repo_name: proj-happycows-s23-6pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjgxNTkzMTk4","is_bot":false,"login":"jessicahsy","name":"Jessica Ho"},"headRefName":"JessicaH-BackgroundFontChange","number":35,"title":"New background and font","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/35"},{"author":{"id":"MDQ6VXNlcjc3NjkzMzkz","is_bot":false,"login":"ykeung","name":"Yuki Keung"},"headRefName":"YukiK-TotalCowsSold","number":31,"title":"Yuki - Added total cows sold to play page and leaderboard table","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/31"},{"author":{"id":"MDQ6VXNlcjc3NzAwMjYz","is_bot":false,"login":"ashleybudman","name":""},"headRefName":"AshleyB-addGithublink","number":30,"title":"Make the words \"available on Github\" link to the repo","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/30"},{"author":{"id":"U_kgDOB7ycjA","is_bot":false,"login":"JacobWoodward2000","name":"Jacob W"},"headRefName":"JacobW-ScaleMilkSalePrice","number":27,"title":"JacobW add option to scale milk sale price","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/27"},{"author":{"id":"U_kgDOB7ycjA","is_bot":false,"login":"JacobWoodward2000","name":"Jacob W"},"headRefName":"JacobW-ScaleCowSalePrice","number":25,"title":"JacobW scale cow sale price","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/25"},{"author":{"id":"MDQ6VXNlcjc3NjkzMzkz","is_bot":false,"login":"ykeung","name":"Yuki Keung"},"headRefName":"YukiK-TotalCowsBought","number":24,"title":"Yuki - Added total cows bought to play page and leaderboard table","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/24"},{"author":{"id":"U_kgDOB7ycjA","is_bot":false,"login":"JacobWoodward2000","name":"Jacob W"},"headRefName":"JacobW-BuySellMultipleCows","number":22,"title":"JacobW buy/sell multiple cows","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/22"},{"author":{"id":"MDQ6VXNlcjc3NjkzMzkz","is_bot":false,"login":"ykeung","name":"Yuki Keung"},"headRefName":"YukiK-FixProfitsTableOverflow","number":18,"title":"Yuki - Fixed profits table overflow bug","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/18"},{"author":{"id":"MDQ6VXNlcjgxMzQxODE5","is_bot":false,"login":"kshitij0407","name":"Kshitij Agarwal"},"headRefName":"KrishA-toastMessage","number":17,"title":"Added toast messages for admin jobs - Krish (6pm-4)","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/17"}]
