
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-happycows-s23-6pm-4
owner: ucsb-cs156-s23
repo_name: proj-happycows-s23-6pm-4
pull_requests: [{"author":{"id":"U_kgDOB7ycjA","is_bot":false,"login":"JacobWoodward2000","name":"Jacob W"},"headRefName":"JacobW-BuyMaxCowsButton","number":78,"title":"JacobW Buy Max Cows Button","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/78"},{"author":{"id":"U_kgDOB7ycjA","is_bot":false,"login":"JacobWoodward2000","name":"Jacob W"},"headRefName":"JacobW-SellAllCowsButton","number":76,"title":"JacobW Sell All Cows Button","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/76"},{"author":{"id":"U_kgDOB7ycjA","is_bot":false,"login":"JacobWoodward2000","name":"Jacob W"},"headRefName":"JacobW-SellTenCowsButton","number":75,"title":"JacobW Sell Ten Cows Button","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/75"},{"author":{"id":"U_kgDOB7ycjA","is_bot":false,"login":"JacobWoodward2000","name":"Jacob W"},"headRefName":"JacobW-BuyTenCowsButton","number":73,"title":"JacobW Buy Ten Cows Button","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/73"},{"author":{"id":"U_kgDOB7ycjA","is_bot":false,"login":"JacobWoodward2000","name":"Jacob W"},"headRefName":"JacobW-AllowVariableNumCowsSoldInFrontend","number":72,"title":"JacobW Allow Variable numCows Sold Frontend","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/72"}]
