
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-happycows-s23-6pm-4
owner: ucsb-cs156-s23
repo_name: proj-happycows-s23-6pm-4
pull_requests: [{"author":{"id":"U_kgDOB7ycjA","is_bot":false,"login":"JacobWoodward2000","name":"Jacob W"},"headRefName":"JacobW-ScaleCowSalePriceFrontendCreate","number":62,"title":"JacobW Scale Cow Sale Price Frontend","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/62"},{"author":{"id":"U_kgDOB7ycjA","is_bot":false,"login":"JacobWoodward2000","name":"Jacob W"},"headRefName":"JacobW-ScaleCowSalePriceFrontendUpdateFixtures","number":61,"title":"JacobW Scale Cow Sale Price Frontend Update Fixtures","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/61"},{"author":{"id":"U_kgDOB7ycjA","is_bot":false,"login":"JacobWoodward2000","name":"Jacob W"},"headRefName":"JacobW-FixStrykerTestsInPlayPage","number":60,"title":"JacobW Fix Stryker Tests in PlayPage.js","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/60"},{"author":{"id":"U_kgDOB7ycjA","is_bot":false,"login":"JacobWoodward2000","name":"Jacob W"},"headRefName":"JacobW-ScaleCowSalePriceBackend","number":58,"title":"JacobW Scale Cow Sale Price Backend","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/58"},{"author":{"id":"U_kgDOB7ycjA","is_bot":false,"login":"JacobWoodward2000","name":"Jacob W"},"headRefName":"JacobW-SellMultipleCowsBackend","number":56,"title":"JacobW Sell Multiple Cows Backend","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/56"},{"author":{"id":"U_kgDOB7ycjA","is_bot":false,"login":"JacobWoodward2000","name":"Jacob W"},"headRefName":"JacobW-BuyMultipleCowsBackend","number":55,"title":"JacobW Buy Multiple Cows Backend","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/55"},{"author":{"id":"MDQ6VXNlcjc3NjkzMzkz","is_bot":false,"login":"ykeung","name":"Yuki Keung"},"headRefName":"YukiK-TotalCowsBoughtSoldUserCommonsController","number":51,"title":"Yuki -  Updated UserCommonsController for total cows bought and sold","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/51"},{"author":{"id":"MDQ6VXNlcjgxNTkzMTk4","is_bot":false,"login":"jessicahsy","name":"Jessica Ho"},"headRefName":"JessicaH-DayNum","number":48,"title":"Jessica h day num","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/48"}]
