
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-happycows-s23-6pm-4
owner: ucsb-cs156-s23
repo_name: proj-happycows-s23-6pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjgxMzQxODE5","is_bot":false,"login":"kshitij0407","name":"Kshitij Agarwal"},"headRefName":"KrishA-toastMessage","number":17,"title":"Added toast messages for admin jobs - Krish","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/17"},{"author":{"id":"MDQ6VXNlcjc3NjkzMzkz","is_bot":false,"login":"ykeung","name":"Yuki Keung"},"headRefName":"YukiK-AddCurrentMilkPrice","number":15,"title":"Add current milk price to the play page","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/15"},{"author":{"id":"MDQ6VXNlcjgxNTkzMTk4","is_bot":false,"login":"jessicahsy","name":"Jessica Ho"},"headRefName":"JessicaH-Update-Link","number":1,"title":"Update README.md","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-4/pull/1"}]
